package aminmaktab;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MainPanel extends javax.swing.JFrame {
    
    public MainPanel() {
        initComponents();                
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(".//res//Logo.jpg"));
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        AllRecordBtn.setVisible(false);
        SpecificBtn.setVisible(false);
        UpdSpecificBtn.setVisible(false);
        DelSpecificBtn.setVisible(false);
        SpecificNameField.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);  
    }
    public MainPanel(String Username)
    {
        initComponents();
        jLabel3.setText(Username);
    }
    
    String TempVal = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ORP = new javax.swing.JButton();
        IE = new javax.swing.JButton();
        CBRP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        AllRecordBtn = new javax.swing.JButton();
        SpecificBtn = new javax.swing.JButton();
        UpdSpecificBtn = new javax.swing.JButton();
        DelSpecificBtn = new javax.swing.JButton();
        SpecificNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amin Maktab | HOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        ORP.setBackground(new java.awt.Color(51, 51, 51));
        ORP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ORP.setForeground(new java.awt.Color(255, 255, 255));
        ORP.setText("Out Reach Projects");
        ORP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORPActionPerformed(evt);
            }
        });

        IE.setBackground(new java.awt.Color(51, 51, 51));
        IE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IE.setForeground(new java.awt.Color(255, 255, 255));
        IE.setText("Inclusive Education");
        IE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IEActionPerformed(evt);
            }
        });

        CBRP.setBackground(new java.awt.Color(51, 51, 51));
        CBRP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CBRP.setForeground(new java.awt.Color(255, 255, 255));
        CBRP.setText("Community Based Rehability Project");
        CBRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ORP)
                    .addComponent(IE)
                    .addComponent(CBRP))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ORP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(CBRP)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amin Maktab Community Project");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        AllRecordBtn.setText("View All Record");
        AllRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRecordBtnActionPerformed(evt);
            }
        });

        SpecificBtn.setText("View Specific");
        SpecificBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecificBtnActionPerformed(evt);
            }
        });

        UpdSpecificBtn.setText("Update Specific");
        UpdSpecificBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdSpecificBtnActionPerformed(evt);
            }
        });

        DelSpecificBtn.setText("Delete Specific");
        DelSpecificBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelSpecificBtnActionPerformed(evt);
            }
        });

        SpecificNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SpecificNameField.setText("Enter Name");
        SpecificNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SpecificNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SpecificNameFieldFocusLost(evt);
            }
        });
        SpecificNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecificNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdSpecificBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(DelSpecificBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpecificBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllRecordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(SpecificNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllRecordBtn)
                    .addComponent(SpecificNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SpecificBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdSpecificBtn)
                .addGap(18, 18, 18)
                .addComponent(DelSpecificBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ORPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORPActionPerformed
        // TODO add your handling code here:
        jLabel4.setText("Amin Maktab | "+ "O.R.P.");
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton1.setText("Index");
        jButton2.setText("Child Activity");
        jButton3.setText("History Datasheet");
        jButton4.setText("Medical Record Sheet");
        jButton5.setText("Psychiatric Consultation");
    }//GEN-LAST:event_ORPActionPerformed

    private void IEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IEActionPerformed
        try 
        {
            // TODO add your handling code here:
            jLabel4.setText("Amin Maktab | "+IE.getText().toString());
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
            
            jDesktopPane1.removeAll();
            HistoryDatasheet_IE hd = new HistoryDatasheet_IE();
            jDesktopPane1.add(hd);
            hd.show();
            try
            {
                hd.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IEActionPerformed

    private void CBRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRPActionPerformed
        try 
        {
            // TODO add your handling code here:
            jLabel4.setText("Amin Maktab | "+"C.B.R.P.");
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
            
            jDesktopPane1.removeAll();
            Newsletter_CBRP nl = new Newsletter_CBRP();
            jDesktopPane1.add(nl);
            nl.show();
            try
            {
                nl.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CBRPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().toString() == "Index")
        {
            jDesktopPane1.removeAll();
            Index_ORP index = new Index_ORP();
            jDesktopPane1.add(index);
            index.show();
            try 
            {
                index.setMaximum(true);
            } 
            catch (PropertyVetoException ex) 
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            TempVal = "Index";
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
        }
        else
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        ChildActivityChart_ORP cac = new ChildActivityChart_ORP();
        jDesktopPane1.add(cac);
        cac.show();
        try 
        {
            cac.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        TempVal = "Child Activity Chart";
        AllRecordBtn.setVisible(true);
        SpecificBtn.setVisible(true);
        UpdSpecificBtn.setVisible(true);
        DelSpecificBtn.setVisible(true);
        SpecificNameField.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try 
        {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            HistoryDatasheet_ORP hd = new HistoryDatasheet_ORP();
            jDesktopPane1.add(hd);
            hd.show();
            try
            {
                hd.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            TempVal = "History Datasheet";
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try 
        {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            MedicalRecordSheet_ORP mrs = new MedicalRecordSheet_ORP();
            jDesktopPane1.add(mrs);
            mrs.show();
            try
            {
                mrs.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            TempVal = "Medical Recordsheet";
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try 
        {
            // TODO add your handling code here:
            jDesktopPane1.removeAll();
            PsychiatricConsultation_ORP pc = new PsychiatricConsultation_ORP();
            jDesktopPane1.add(pc);
            pc.show();
            try
            {
                pc.setMaximum(true);
            }
            catch (PropertyVetoException ex)
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            TempVal = "Psychiatric Consultation";
            AllRecordBtn.setVisible(true);
            SpecificBtn.setVisible(true);
            UpdSpecificBtn.setVisible(true);
            DelSpecificBtn.setVisible(true);
            SpecificNameField.setVisible(true);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SpecificNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SpecificNameFieldFocusGained
        // TODO add your handling code here:
        if(SpecificNameField.getText().toString().equals("Enter Name"))
        {
            SpecificNameField.setText("");
        }
    }//GEN-LAST:event_SpecificNameFieldFocusGained

    private void SpecificNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SpecificNameFieldFocusLost
        // TODO add your handling code here:
        if(SpecificNameField.getText().toString().equals(""))
        {
            SpecificNameField.setText("Enter Name");
        }
    }//GEN-LAST:event_SpecificNameFieldFocusLost

    private void SpecificBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecificBtnActionPerformed
        // TODO add your handling code here:
        String Name = SpecificNameField.getText().toString();
        if(Name.isEmpty())
        {
            
        }
        else
        {
            if(jLabel4.getText().toString().equals("Amin Maktab | O.R.P."))
            {
                if(TempVal.equals("Index"))
                {
                    jDesktopPane1.removeAll();
                    Index_ORP IR = new Index_ORP(Name, "Read");
                    jDesktopPane1.add(IR);
                    IR.show();
                    try 
                    {
                        IR.setMaximum(true);
                    } 
                    catch (PropertyVetoException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Child Activity Chart"))
                {
                
                }
                else if(TempVal.equals("History Datasheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        HistoryDatasheet_ORP HDR = new HistoryDatasheet_ORP(Name,"Read");
                        jDesktopPane1.add(HDR);
                        HDR.show();
                        try
                        {
                            HDR.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Medical Recordsheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        MedicalRecordSheet_ORP MRSR = new MedicalRecordSheet_ORP(Name,"Read");
                        jDesktopPane1.add(MRSR);
                        MRSR.show();
                        try
                        {
                            MRSR.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Psychiatric Consultation"))
                {
                    jDesktopPane1.removeAll();
                    PsychiatricConsultation_ORP_Read PCR = new PsychiatricConsultation_ORP_Read(Name);
                    jDesktopPane1.add(PCR);
                    PCR.show();
                    try 
                    {
                        PCR.setMaximum(true);
                    } 
                    catch (PropertyVetoException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else if(jLabel4.getText().toString().equals("Amin Maktab | Inclusive Education"))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    HistoryDatasheet_IE HDR = new HistoryDatasheet_IE(Name,"Read");
                    jDesktopPane1.add(HDR);
                    HDR.show();
                    try
                    {
                        HDR.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(jLabel4.getText().toString().equals("Amin Maktab | C.B.R.P."))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    Newsletter_CBRP NLR = new Newsletter_CBRP(Name,"Read");
                    jDesktopPane1.add(NLR);
                    NLR.show();
                    try
                    {
                        NLR.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_SpecificBtnActionPerformed

    private void UpdSpecificBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdSpecificBtnActionPerformed
        // TODO add your handling code here:
        String Name = SpecificNameField.getText().toString();
        if(Name.isEmpty())
        {
            
        }
        else
        {
            if(jLabel4.getText().toString().equals("Amin Maktab | O.R.P."))
            {
                if(TempVal.equals("Index"))
                {
                    jDesktopPane1.removeAll();
                    Index_ORP IU = new Index_ORP(Name, "Update");
                    jDesktopPane1.add(IU);
                    IU.show();
                    try 
                    {
                        IU.setMaximum(true);
                    } 
                    catch (PropertyVetoException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Child Activity Chart"))
                {
                
                }
                else if(TempVal.equals("History Datasheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        HistoryDatasheet_ORP HDU = new HistoryDatasheet_ORP(Name,"Update");
                        jDesktopPane1.add(HDU);
                        HDU.show();
                        try
                        {
                            HDU.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Medical Recordsheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        MedicalRecordSheet_ORP MRSU = new MedicalRecordSheet_ORP(Name,"Update");
                        jDesktopPane1.add(MRSU);
                        MRSU.show();
                        try
                        {
                            MRSU.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Psychiatric Consultation"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        PsychiatricConsultation_ORP_Update PCU = new PsychiatricConsultation_ORP_Update(Name);
                        jDesktopPane1.add(PCU);
                        PCU.show();
                        try
                        {
                            PCU.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else if(jLabel4.getText().toString().equals("Amin Maktab | Inclusive Education"))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    HistoryDatasheet_IE HDU = new HistoryDatasheet_IE(Name,"Update");
                    jDesktopPane1.add(HDU);
                    HDU.show();
                    try
                    {
                        HDU.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(jLabel4.getText().toString().equals("Amin Maktab | C.B.R.P."))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    Newsletter_CBRP NLU = new Newsletter_CBRP(Name,"Update");
                    jDesktopPane1.add(NLU);
                    NLU.show();
                    try
                    {
                        NLU.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_UpdSpecificBtnActionPerformed

    private void AllRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRecordBtnActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().toString().equals("Amin Maktab | O.R.P."))
        {
            if(TempVal.equals("Index"))
            {
                jDesktopPane1.removeAll();
                Index_ORP_AllRec IAR = new Index_ORP_AllRec();
                jDesktopPane1.add(IAR);
                IAR.show();
                try 
                {
                    IAR.setMaximum(true);
                } 
                catch (PropertyVetoException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(TempVal.equals("Child Activity Chart"))
            {

            }
            else if(TempVal.equals("History Datasheet"))
            {
                jDesktopPane1.removeAll();
                HistoryDatasheet_ORP_AllRec HDAR = new HistoryDatasheet_ORP_AllRec();
                jDesktopPane1.add(HDAR);
                HDAR.show();
                try 
                {
                    HDAR.setMaximum(true);
                } 
                catch (PropertyVetoException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(TempVal.equals("Medical Recordsheet"))
            {
                jDesktopPane1.removeAll();
                MedicalRecordSheet_ORP_AllRec MRAR = new MedicalRecordSheet_ORP_AllRec();
                jDesktopPane1.add(MRAR);
                MRAR.show();
                try 
                {
                    MRAR.setMaximum(true);
                } 
                catch (PropertyVetoException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(TempVal.equals("Psychiatric Consultation"))
            {
                jDesktopPane1.removeAll();
                PsychiatricConsultation_ORP_AllRec PCAR = new PsychiatricConsultation_ORP_AllRec();
                jDesktopPane1.add(PCAR);
                PCAR.show();
                try 
                {
                    PCAR.setMaximum(true);
                } 
                catch (PropertyVetoException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(jLabel4.getText().toString().equals("Amin Maktab | Inclusive Education"))
        {
            jDesktopPane1.removeAll();
            HistoryDatasheet_IE_AllRec HDIEAR = new HistoryDatasheet_IE_AllRec();
            jDesktopPane1.add(HDIEAR);
            HDIEAR.show();
            try 
            {
                HDIEAR.setMaximum(true);
            } 
            catch (PropertyVetoException ex) 
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(jLabel4.getText().toString().equals("Amin Maktab | C.B.R.P."))
        {
            jDesktopPane1.removeAll();
            Newsletter_CBRP_AllRec NAR = new Newsletter_CBRP_AllRec();
            jDesktopPane1.add(NAR);
            NAR.show();
            try 
            {
                NAR.setMaximum(true);
            } 
            catch (PropertyVetoException ex) 
            {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AllRecordBtnActionPerformed

    private void DelSpecificBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelSpecificBtnActionPerformed
        // TODO add your handling code here:
        String Name = SpecificNameField.getText().toString();
        if(Name.isEmpty())
        {
            
        }
        else
        {
            if(jLabel4.getText().toString().equals("Amin Maktab | O.R.P."))
            {
                if(TempVal.equals("Index"))
                {
                    jDesktopPane1.removeAll();
                    Index_ORP ID = new Index_ORP(Name, "Delete");
                    jDesktopPane1.add(ID);
                    ID.show();
                    try 
                    {
                        ID.setMaximum(true);
                    } 
                    catch (PropertyVetoException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Child Activity Chart"))
                {

                }
                else if(TempVal.equals("History Datasheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        HistoryDatasheet_ORP HDD = new HistoryDatasheet_ORP(Name,"Delete");
                        jDesktopPane1.add(HDD);
                        HDD.show();
                        try
                        {
                            HDD.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Medical Recordsheet"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        MedicalRecordSheet_ORP MRSD = new MedicalRecordSheet_ORP(Name,"Delete");
                        jDesktopPane1.add(MRSD);
                        MRSD.show();
                        try
                        {
                            MRSD.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                    catch (ParseException ex) 
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(TempVal.equals("Psychiatric Consultation"))
                {
                    try 
                    {
                        jDesktopPane1.removeAll();
                        PsychiatricConsultation_ORP PCD = new PsychiatricConsultation_ORP(Name, "Delete");
                        jDesktopPane1.add(PCD);
                        PCD.show();
                        try
                        {
                            PCD.setMaximum(true);
                        }
                        catch (PropertyVetoException ex)
                        {
                            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    catch (ParseException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else if(jLabel4.getText().toString().equals("Amin Maktab | Inclusive Education"))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    HistoryDatasheet_IE HDD = new HistoryDatasheet_IE(Name,"Delete");
                    jDesktopPane1.add(HDD);
                    HDD.show();
                    try
                    {
                        HDD.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(jLabel4.getText().toString().equals("Amin Maktab | C.B.R.P."))
            {
                try 
                {
                    jDesktopPane1.removeAll();
                    Newsletter_CBRP NLD = new Newsletter_CBRP(Name,"Delete");
                    jDesktopPane1.add(NLD);
                    NLD.show();
                    try
                    {
                        NLD.setMaximum(true);
                    }
                    catch (PropertyVetoException ex)
                    {
                        Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_DelSpecificBtnActionPerformed

    private void SpecificNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecificNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecificNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllRecordBtn;
    private javax.swing.JButton CBRP;
    private javax.swing.JButton DelSpecificBtn;
    private javax.swing.JButton IE;
    private javax.swing.JButton ORP;
    private javax.swing.JButton SpecificBtn;
    private javax.swing.JTextField SpecificNameField;
    private javax.swing.JButton UpdSpecificBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
