/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aminmaktab;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABC
 */
public class Newsletter_CBRP_AllRec extends javax.swing.JInternalFrame {

    /**
     * Creates new form Newsletter_CBRP_AllRec
     */
    public Newsletter_CBRP_AllRec() {
        initComponents();
        try
        {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            File myFile = new File("Newsletter_CBRP.txt");
            if(myFile.exists())
            {
                Scanner myRead = new Scanner(myFile);
                boolean check = false;
                while(myRead.hasNextLine())
                {
                    String[] dataRow = {
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), 
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), 
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), 
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), 
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), 
                        myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(), myRead.nextLine(),
                        myRead.nextLine(), myRead.nextLine()};
                    model.addRow(dataRow);
                    if(myRead.hasNextLine())
                    {
                        myRead.nextLine();
                    }
                    check = true;
                }
                if(check == true)
                {
                    JFrame j = new JFrame();
                    JOptionPane.showMessageDialog(j,"Successfully Displayed Data...");
                }
                if(check == false)
                {
                    JFrame j = new JFrame();
                    JOptionPane.showMessageDialog(j,"Error: Data Not Found...");
                }
                myRead.close();
            }
            else
            {
                myFile.createNewFile();
            }
        }
        catch(IOException ex)
        {
            System.out.println("Error");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("NEWSLETTER | CBRP");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Registration No", "Date", "Age", "Gender", "Date of Birth", "Number of Siblings", "Phone Number", "Home Address", "Child's Current Issues", "Father's Name", "Father's Age", "Father's Occupation", "Mother's Name", "Mother's Age", "Mother's Occupation", "Relation Betweel Parents", "Neck Control", "Sitting", "Walking", "Speech Single Word", "Complete Sentences", "Bladder & Bowel Control", "Eating Without Help", "Dressing Up Without Help", "Chil'd Favourites", "Attended School Previously", "Class", "Medical Examination", "Psychiatry", "Physiotherapy", "Other"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(50);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
